# Generated by Django 5.1 on 2024-10-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id_privilegio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Privilegio',
                'verbose_name_plural': 'Privilegios',
                'db_table': 'tbl_privilegios',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'tbl_roles',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'tbl_trabajadores',
            },
        ),
        migrations.CreateModel(
            name='RolPrivilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.privilegio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.rol')),
            ],
            options={
                'verbose_name': 'Rol-Privilegio',
                'verbose_name_plural': 'Roles-Privilegios',
                'db_table': 'tbl_rol_privilegios',
                'unique_together': {('rol', 'privilegio')},
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='privilegios',
            field=models.ManyToManyField(related_name='roles', through='AppProyecto.RolPrivilegio', to='AppProyecto.privilegio'),
        ),
        migrations.CreateModel(
            name='DatosLaborales',
            fields=[
                ('id_datos_laborales', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.trabajador')),
            ],
            options={
                'verbose_name': 'Dato Laboral',
                'verbose_name_plural': 'Datos Laborales',
                'db_table': 'tbl_datosLaborales',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.trabajador')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
                'db_table': 'tbl_contactosEmergencia',
            },
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id_carga_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.trabajador')),
            ],
            options={
                'verbose_name': 'Carga Familiar',
                'verbose_name_plural': 'Cargas Familiares',
                'db_table': 'tbl_cargasFamiliares',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppProyecto.rol')),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.trabajador')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tbl_usuarios',
            },
        ),
    ]
