# Generated by Django 5.1 on 2024-11-05 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargafamiliar',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppProyecto.genero'),
        ),
    ]
