# Generated by Django 5.1 on 2024-11-19 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_alter_cargafamiliar_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')]),
        ),
    ]
