# Generated by Django 5.1 on 2024-11-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0006_usuario_token_recuperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'db_table': 'tbl_parentesco',
            },
        ),
        migrations.AlterField(
            model_name='cargafamiliar',
            name='parentesco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppProyecto.parentesco'),
        ),
    ]
