# Generated by Django 5.1 on 2024-11-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0007_parentesco_alter_cargafamiliar_parentesco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentesco',
            old_name='id',
            new_name='id_parentesco',
        ),
    ]
